### ISSUE TITLE
Fabric Version

### ISSUE THREAD

**Issue by Android789515** [CompeyDev/touch-grass-reminder#2]
This is an incredible idea for a mod.  I am running on Fabric, are you willing to have a Fabric version or will this work already?

**Comment by CompeyDev** [comment]
It is currently a quilt exclusive, and I do not plan on porting it in the near future to Fabric due to how it almost entirely depends on Quilt's API. Quilt just generally had a nice dx, and hence I decided to write it as a Quilt exclusive.

However, it is possible to run Fabric mods on Quilt (not the other way around), so you could try swapping your modloader to Quilt without much migration, if you would like to use this mod.

**Comment by Android789515** [comment]
> It is currently a quilt exclusive, and I do not plan on porting it in the near future to Fabric due to how it almost entirely depends on Quilt's API. Quilt just generally had a nice dx, and hence I decided to write it as a Quilt exclusive.
> 
> However, it is possible to run Fabric mods on Quilt (not the other way around), so you could try swapping your modloader to Quilt without much migration, if you would like to use this mod.

Not a bad idea.  I'll give it a try.
